services:
  data_engine:
    build: .
    volumes:
      # 只挂载源代码、数据和日志目录，而不是整个项目目录
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
      - ./scripts:/app/scripts
    # 设置环境变量
    environment:
      # 设置 Python 不缓冲标准输出
      - PYTHONUNBUFFERED=1
    # 保持容器运行
    command: tail -f /dev/null
    # 设置容器重启策略
    restart: unless-stopped
