version: '3.8'

services:
  data_engine:
    build: .
    volumes:
      # 挂载当前目录到容器中  
      - .:/app
    # 设置环境变量
    environment:
      # 设置 Python 不缓冲标准输出
      - PYTHONUNBUFFERED=1
    # 保持容器运行
    command: tail -f /dev/null
    # 设置容器重启策略
    restart: unless-stopped
